import Link from "next/link";
import { ArrowUpRight, CreditCard, Landmark, PiggyBank, TrendingUp, Wallet } from "lucide-react";
import { CashFlowChart } from "@/components/charts/cash-flow-chart";
import { ExpenseDistribution } from "@/components/charts/expense-distribution";
import { KpiCard } from "@/components/finance/kpi-card";
import { TransactionTable } from "@/components/finance/transaction-table";
import { BudgetBoard } from "@/components/finance/budget-board";
import { insights } from "@/data/finance";
import { PageHeader } from "@/components/page-header";
import { cn } from "@/lib/utils";

export function DashboardScreen() {
  return <div className="space-y-8 lg:space-y-10"><PageHeader eyebrow="October 2026" title="Good morning, Alex" description="A considered view of your financial position across every account." actions={<button className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm hover:bg-primary-hover"><Wallet className="size-4" />Add transaction</button>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="Total balance" value="EUR 82,709" change="8.4%" positive icon={Landmark} /><KpiCard label="Monthly income" value="EUR 9,100" change="6.2%" positive icon={TrendingUp} /><KpiCard label="Monthly expenses" value="EUR 4,550" change="12.0%" positive={false} icon={CreditCard} muted /><KpiCard label="Net cash flow" value="EUR 4,550" change="EUR 310" positive icon={Wallet} /><KpiCard label="Savings rate" value="17.0%" change="5.0 pts" positive icon={PiggyBank} /></section><section className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,.8fr)]"><CashFlowChart /><ExpenseDistribution /></section><section className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(340px,.8fr)]"><TransactionTable compact /><BudgetBoard compact /></section><section className="rounded-xl border border-border-subtle bg-card p-5 card-shadow sm:p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-semibold tracking-[-.025em]">Financial signals</h2><p className="mt-1 text-sm text-muted-foreground">Focused observations from this month&apos;s activity.</p></div><Link href="/assistant" className="hidden items-center gap-1 text-sm font-medium text-primary hover:text-primary-hover sm:flex">Ask Ledgerly AI <ArrowUpRight className="size-3.5" /></Link></div><div className="grid gap-3 md:grid-cols-3">{insights.map((insight) => <article key={insight.id} className="rounded-lg border border-border-subtle bg-card p-4 transition-colors hover:bg-hover-surface"><span className={cn("inline-flex size-8 items-center justify-center rounded-lg text-sm", insight.trend === "positive" ? "bg-positive/10 text-positive" : insight.trend === "warning" ? "bg-warning/10 text-warning" : "bg-primary-soft text-primary")}>{insight.icon === "arrow" ? "up" : insight.icon === "wallet" ? "EUR" : "AI"}</span><h3 className="mt-3 text-sm font-semibold">{insight.title}</h3><p className="mt-1.5 text-sm leading-5 text-muted-foreground">{insight.description}</p></article>)}</div></section></div>;
}
