"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { BarChart3, Bell, Bot, CircleHelp, Command, CreditCard, Landmark, LayoutDashboard, Menu, Moon, PanelLeftClose, PanelLeftOpen, ReceiptText, Search, Settings, Sun, WalletCards, X } from "lucide-react";
import { useTheme } from "next-themes";
import { cn } from "@/lib/utils";

const navigation = [
  { label: "Overview", href: "/dashboard", icon: LayoutDashboard }, { label: "Transactions", href: "/transactions", icon: ReceiptText }, { label: "Accounts", href: "/accounts", icon: Landmark }, { label: "Analytics", href: "/analytics", icon: BarChart3 }, { label: "Budget", href: "/budget", icon: WalletCards }, { label: "AI Assistant", href: "/assistant", icon: Bot, special: true }, { label: "Reports", href: "/reports", icon: CreditCard }, { label: "Notifications", href: "/notifications", icon: Bell }, { label: "Settings", href: "/settings", icon: Settings },
];

function Logo({ condensed = false }: { condensed?: boolean }) { return <Link href="/dashboard" className="flex min-w-0 items-center gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary text-sm font-semibold text-primary-foreground">L</span>{!condensed && <span className="truncate text-[17px] font-semibold tracking-[-.035em]">ledgerly</span>}</Link>; }
function ThemeToggle() { const { resolvedTheme, setTheme } = useTheme(); return <button onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")} aria-label="Toggle color mode" className="grid size-9 place-items-center rounded-lg text-muted-foreground hover:bg-hover-surface hover:text-foreground"><Sun className="hidden size-4 dark:block" /><Moon className="size-4 dark:hidden" /></button>; }

function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); if (open) { document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); } }, [onClose, open]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[60] grid place-items-start bg-[#101828]/25 p-4 pt-[16vh] backdrop-blur-[2px]" onMouseDown={onClose}><section role="dialog" aria-modal="true" aria-label="Command menu" onMouseDown={(event) => event.stopPropagation()} className="w-full max-w-xl overflow-hidden rounded-xl border bg-card card-shadow animate-in fade-in zoom-in-95 duration-150"><div className="flex items-center gap-3 border-b px-4 py-3"><Search className="size-4 text-muted-foreground" /><input autoFocus placeholder="Search transactions, accounts, reports..." className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><kbd className="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">ESC</kbd></div><div className="p-2"><p className="px-2 py-1.5 text-[11px] font-semibold uppercase tracking-[.1em] text-muted-foreground">Quick navigation</p>{navigation.slice(0, 6).map(({ label, href, icon: Icon }) => <Link key={href} onClick={onClose} href={href} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm hover:bg-hover-surface"><Icon className="size-4 text-muted-foreground" />{label}</Link>)}</div></section></div>;
}

function NavContent({ condensed, closeMobile }: { condensed: boolean; closeMobile?: () => void }) {
  const pathname = usePathname();
  return <><div className={cn("flex h-16 items-center", condensed ? "justify-center" : "px-4")}><Logo condensed={condensed} /></div><nav aria-label="Primary navigation" className="flex flex-1 flex-col gap-1 px-2 py-3">{navigation.map(({ label, href, icon: Icon, special }) => { const active = pathname === href; return <Link key={href} href={href} onClick={closeMobile} title={condensed ? label : undefined} className={cn("group flex items-center rounded-lg px-3 py-2.5 text-[13px] font-medium transition-colors", condensed && "justify-center px-2", active ? "bg-primary-soft text-primary" : special ? "text-primary hover:bg-primary-soft" : "text-muted-foreground hover:bg-hover-surface hover:text-foreground")}><Icon className="size-[17px] shrink-0" /><span className={cn("ml-3", condensed && "sr-only")}>{label}</span>{label === "Notifications" && !condensed && <span className="ml-auto size-1.5 rounded-full bg-negative" />}</Link>; })}</nav><div className="border-t border-border-subtle p-2"><a href="mailto:support@ledgerly.demo" className={cn("flex items-center rounded-lg px-3 py-2.5 text-[13px] font-medium text-muted-foreground hover:bg-hover-surface hover:text-foreground", condensed && "justify-center px-2")}><CircleHelp className="size-[17px]" /><span className={cn("ml-3", condensed && "sr-only")}>Help & support</span></a><div className={cn("mt-1 flex items-center rounded-lg px-3 py-2.5", condensed && "justify-center px-2")}><div className="grid size-8 shrink-0 place-items-center rounded-full bg-primary-soft text-[11px] font-semibold text-primary">AM</div><div className={cn("ml-2.5 min-w-0", condensed && "hidden")}><p className="truncate text-[13px] font-medium">Alex Morgan</p><p className="truncate text-[11px] text-muted-foreground">Personal workspace</p></div></div></div></>;
}

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const assistantRoute = pathname === "/assistant"; const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false);
  useEffect(() => { const openCommand = (event: KeyboardEvent) => { if (!assistantRoute && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen(true); } }; document.addEventListener("keydown", openCommand); return () => document.removeEventListener("keydown", openCommand); }, [assistantRoute]);
  if (assistantRoute) return <main className="fixed inset-0 overflow-hidden bg-card">{children}</main>;
  return <div className="min-h-screen bg-background"><aside className={cn("fixed inset-y-0 left-0 z-40 hidden flex-col border-r border-border-subtle bg-sidebar transition-[width] duration-200 lg:flex", collapsed ? "w-[72px]" : "w-[240px]")}><NavContent condensed={collapsed} /><button onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} className="absolute -right-3 top-6 grid size-6 place-items-center rounded-full border bg-card text-muted-foreground card-shadow hover:text-foreground">{collapsed ? <PanelLeftOpen className="size-3.5" /> : <PanelLeftClose className="size-3.5" />}</button></aside>{mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" onClick={() => setMobileOpen(false)} className="absolute inset-0 bg-[#101828]/35" /><aside className="relative flex h-full w-[280px] flex-col bg-sidebar shadow-xl"><div className="absolute right-3 top-3"><button onClick={() => setMobileOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-hover-surface"><X className="size-4" /></button></div><NavContent condensed={false} closeMobile={() => setMobileOpen(false)} /></aside></div>}<main className={cn("min-h-screen transition-[padding] duration-200", collapsed ? "lg:pl-[72px]" : "lg:pl-[240px]")}><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-border-subtle bg-background/85 px-4 backdrop-blur-xl sm:px-6"><button onClick={() => setMobileOpen(true)} aria-label="Open navigation" className="grid size-9 place-items-center rounded-lg text-muted-foreground hover:bg-hover-surface lg:hidden"><Menu className="size-5" /></button><button onClick={() => setCommandOpen(true)} className="hidden h-9 w-full max-w-sm items-center gap-2 rounded-lg border border-border-subtle bg-card px-3 text-left text-[13px] text-muted-foreground hover:border-border hover:bg-hover-surface md:flex"><Search className="size-4" /><span>Search or jump to...</span><kbd className="ml-auto inline-flex items-center gap-0.5 rounded border bg-muted px-1.5 py-0.5 text-[10px]"><Command className="size-2.5" />K</kbd></button><div className="ml-auto flex items-center gap-1"><ThemeToggle /><Link href="/notifications" aria-label="Notifications" className="relative grid size-9 place-items-center rounded-lg text-muted-foreground hover:bg-hover-surface hover:text-foreground"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-negative" /></Link><div className="ml-1 grid size-8 place-items-center rounded-full bg-primary-soft text-[11px] font-semibold text-primary">AM</div></div></header><div className="mx-auto max-w-[1440px] p-5 sm:p-6 lg:p-8">{children}</div></main><CommandPalette open={commandOpen} onClose={() => setCommandOpen(false)} /></div>;
}
