"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { cashFlowData } from "@/data/finance";
import { cn } from "@/lib/utils";

const periods = ["7D", "30D", "3M", "6M", "1Y"] as const;

export function CashFlowChart({ expanded = false }: { expanded?: boolean }) {
  const [period, setPeriod] = useState<(typeof periods)[number]>(expanded ? "1Y" : "6M");
  const data = useMemo(() => cashFlowData.slice(-(period === "7D" ? 3 : period === "30D" ? 4 : period === "3M" ? 3 : period === "6M" ? 6 : 7)), [period]);
  return <section className="rounded-xl border border-border-subtle bg-card p-5 card-shadow sm:p-6"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-semibold tracking-tight">Cash flow</h2><p className="mt-1 text-sm text-muted-foreground">Income and expenses over time</p></div><div className="flex rounded-lg bg-muted p-1">{periods.map((item) => <button key={item} onClick={() => setPeriod(item)} className={cn("rounded-md px-2.5 py-1 text-xs font-medium transition", period === item ? "bg-card text-foreground card-shadow" : "text-muted-foreground hover:text-foreground")}>{item}</button>)}</div></div><div className={expanded ? "h-[340px]" : "h-[275px]"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 4, right: 4, left: -18, bottom: 0 }}><defs><linearGradient id="incomeGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#635BFF" stopOpacity={0.2} /><stop offset="100%" stopColor="#635BFF" stopOpacity={0} /></linearGradient><linearGradient id="expenseGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#F04438" stopOpacity={0.13} /><stop offset="100%" stopColor="#F04438" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="currentColor" className="text-border" strokeDasharray="3 3" /><XAxis dataKey="label" axisLine={false} tickLine={false} tickMargin={10} className="fill-muted-foreground text-xs" /><YAxis axisLine={false} tickLine={false} width={52} tickFormatter={(value) => `EUR ${value / 1000}k`} className="fill-muted-foreground text-xs" /><Tooltip cursor={{ stroke: "#A5ADBA", strokeWidth: 1 }} contentStyle={{ borderRadius: 8, border: "1px solid var(--border)", background: "var(--card)", color: "var(--foreground)", boxShadow: "0 8px 18px rgba(16,24,40,.08)" }} labelStyle={{ color: "var(--muted-foreground)", marginBottom: 6 }} /><Area type="monotone" dataKey="income" name="Income" stroke="#635BFF" strokeWidth={2} fill="url(#incomeGradient)" /><Area type="monotone" dataKey="expenses" name="Expenses" stroke="#F04438" strokeWidth={2} fill="url(#expenseGradient)" /></AreaChart></ResponsiveContainer></div><div className="mt-2 flex items-center justify-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-primary" />Income</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-negative" />Expenses</span></div></section>;
}
