"use client";

import { useState } from "react";
import { CircleAlert, Plus, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { BudgetBoard } from "@/components/finance/budget-board";

export function BudgetScreen() {
  const [open, setOpen] = useState(false);
  return <div className="space-y-6 lg:space-y-8"><PageHeader eyebrow="October 2026" title="Budget" description="Stay intentional with everyday spending without losing flexibility." actions={<button onClick={() => setOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground"><Plus className="size-4" />Create budget</button>} /><section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">Planned this month</p><p className="mt-2 text-3xl font-semibold tracking-tight">EUR 1,450</p><p className="mt-2 text-xs text-muted-foreground">Across 4 active category budgets</p></article><article className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">Spent so far</p><p className="mt-2 text-3xl font-semibold tracking-tight">EUR 1,180</p><p className="mt-2 text-xs font-medium text-emerald-600">EUR 270 remains planned</p></article><article className="rounded-2xl border bg-amber-500/[.06] p-5"><div className="flex items-center gap-2 text-amber-700 dark:text-amber-300"><CircleAlert className="size-4" /><p className="text-sm font-medium">One category needs attention</p></div><p className="mt-2 text-sm text-muted-foreground">Shopping has exceeded its monthly allocation by EUR 50.</p></article></section><BudgetBoard open={open} onOpenChange={setOpen} /><section className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-4" /></span><div><h2 className="font-semibold">A calmer way to budget</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Use Ledgerly AI when you want a suggested monthly plan based on your actual financial patterns, not arbitrary category percentages.</p><a href="/assistant" className="mt-3 inline-block text-sm font-medium text-primary hover:underline">Ask for a budget plan -&gt;</a></div></div></section></div>;
}
